name: Deploy to EC2

on:
  push:
    branches:
      - test1  # Trigger only on changes to the test1 branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Start SSH agent and add private key
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: SSH into EC2 and run deployment commands
      - name: Deploy app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
            echo "Current directory: $(pwd)"
            cd /home/ubuntu/node-demo-/test2
            echo "Changed directory to: $(pwd)"
            echo "Before reset, git status:"
            git status
            git fetch origin test1
            git reset --hard origin/test1
            echo "After reset, git status:"
            git status
            npm install
            pkill node || true
            nohup npm start > output.log 2>&1 &
            echo "Deployment completed"
            cat output.log  # Show the contents of the output log
          EOF
