name: Deploy to EC2

on:
  push:
    branches:
      - test1

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the SSH agent with your private key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Using the secret for SSH private key

      # Step 3: Add the EC2 host to the known hosts to avoid SSH warnings
      - name: Ensure EC2 is in known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.EC2_HOST }} "cd /path/to/your/project && git pull origin main && npm install && npm start"
