name: Deploy to EC2

on:
  push:
    branches:
      - test1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync folder1 to EC2
        run: |
          ./sync_script.sh  # Point to your sync script here
