name: Deploy to EC2 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node.js App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH known hosts
        run: |
          # Ensure that the EC2 host is in known hosts to prevent SSH warning
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Deploy Node.js app to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}  # Public IP or DNS of your EC2 instance
          username: ${{ secrets.USERNAME }}  # EC2 SSH username (e.g., ubuntu or ec2-user)
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH private key (add to GitHub secrets)
          port: 22  # Default SSH port
          script: |
            # Enable debugging
            set -x

            # Update system packages
            sudo apt-get update

            # Install Node.js, npm, and git
            sudo apt-get install -y nodejs npm git

            # Clone the latest repo and install dependencies
            rm -rf node-demo-
            git clone https://github.com/prem7443/node-demo-.git
            cd node-demo-
            npm install

            # Run the app in the background
            pkill node || true
            nohup node index.js > app.log 2>&1 &
