name: Deploy Node App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Node.js app to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Add EC2 to known hosts to prevent SSH warning
            ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

            # Update system packages and install Node.js and npm if not installed
            sudo apt-get update
            sudo apt-get install -y nodejs npm git

            # Clone the latest repo and install dependencies
            rm -rf node-demo-
            git clone https://github.com/prem7443/node-demo-.git
            cd node-demo-
            npm install

            # Run the app in the background
            pkill node || true
            nohup node index.js > app.log 2>&1 &
